user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
