# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
      projectTwo:
            entity:
                class: UserBundle:User




    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/
            anonymous: ~
            provider: projectTwo
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: logout
                target: /login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      - {path: ^/user/login,roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/user,roles: ROLE_ADMIN}
