empresa_homepage:
    path:     /
    defaults: { _controller: EmpresaBundle:Default:index }
all_empresa:
    path:     /Empresa/all
    defaults: { _controller: EmpresaBundle:Empresa:all }

all_Alumnos:
    path:     /Alumnos/all
    defaults: { _controller: EmpresaBundle:Alumnos:all }

new_empresa:
    path:     /Empresa/new
    defaults: { _controller: EmpresaBundle:Empresa:new }

