empresa_homepage:
    path:     /
    defaults: { _controller: EmpresaBundle:Default:index }
all_empresa:
    path:     /Empresa/all
    defaults: { _controller: EmpresaBundle:Empresa:all }

all_Alumnos:
    path:     /Alumnos/all
    defaults: { _controller: EmpresaBundle:Alumnos:all }

all_Profesores:
    path:     /Profesor/all
    defaults: { _controller: EmpresaBundle:Profesor:all }

new_empresa:
    path:     /Empresa/new
    defaults: { _controller: EmpresaBundle:Empresa:new }

new_Profesor:
    path:     /Profesor/new
    defaults: { _controller: EmpresaBundle:Profesor:new }

search_empresa:
    path:     /apiEmpresa/all
    defaults: { _controller: EmpresaBundle:ApiEmpresa:allEmpresa}
    methods:  [GET]


search_profesor:
    path:     /apiProfesores/all
    defaults: { _controller: EmpresaBundle:ApiProfesores:allProfesores}
    methods:  [GET]



